remote_theme: chrisrhymes/bulma-clean-theme
title: Ally - The Friendly Discord Bot
permalink: /blog/:categories/:year/:month/:day/:title/
footer_menu: footer
paginate: 5
paginate_path: "/blog/page:num"

exclude: [ ".vscode", ".gitignore", "LICENSE", "README.md", "Gemfile", "Gemfile.lock"]

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
  - scope:
      path: ""
      type: posts
    values: 
      show_sidebar: true