remote_theme: chrisrhymes/bulma-clean-theme

title: Ally - The Friendly Discord Bot
permalink: pretty
footer_menu: footer

exclude: [ ".vscode", ".gitignore", "LICENSE", "README.md", "Gemfile", "Gemfile.lock"]

paginate: 5
paginate_path: "/blog/page:num"

defaults:
  - scope:
      path: "_posts"
    values: 
      layout: post
      toc: true
      toc_name: Sections